[package]
authors = ["Tim Robinson <tim.g.robinson@gmail.com>"]
name = "os"
version = "0.0.0"

[lib]
path = "lib.rs"
test = false

[dependencies]
libc = { path = "../liblibc" }
syscall = { path = "../libsyscall" }
