[package]
authors = ["The Rust Project Developers"]
name = "collections"
version = "0.0.0"

[lib]
name = "collections"
path = "lib.rs"

[dependencies]
alloc = { path = "../liballoc" }
core = { path = "../libcore" }
std_unicode = { path = "../libstd_unicode" }

[[test]]
name = "collectionstests"
path = "../libcollections/tests/lib.rs"

[[bench]]
name = "collectionsbenches"
path = "../libcollections/benches/lib.rs"
