[package]
authors = ["The Rust Project Developers"]
name = "collections"
version = "0.0.0"

[lib]
name = "collections"
path = "lib.rs"

[dependencies]
alloc = { path = "../liballoc" }
core = { path = "../libcore" }
rustc_unicode = { path = "../librustc_unicode" }

[[test]]
name = "collectionstest"
path = "../libcollectionstest/lib.rs"
