version: 2
updates:
- package-ecosystem: cargo
  directory: "/src"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: cargo
  directory: "/src/kernel"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
