addons:
    apt:
        packages:
            - genisoimage
            - libfdt-dev
            - libglib2.0-dev
            - libpixman-1-dev
            - python3-pip
            - python3-setuptools
            - zlib1g-dev

before_install: ./travis-setup.sh

cache:
    directories:
        - 3rdparty

os: linux
dist: bionic

git:
    submodules: false

language: c
script: ./travis.sh
