[package]
name = "graphics"
version = "0.0.0"
authors = ["Tim Robinson <tim.g.robinson@gmail.com>"]

[lib]
path = "lib.rs"
test = false

[dependencies]
cairo = { path = "../libcairo" }
std = { path = "../libstd" }
