[package]
name = "graphics"
version = "0.0.0"
authors = ["Tim Robinson <tim.g.robinson@gmail.com>"]

[lib]
path = "lib.rs"
test = false

[dependencies]
cairo = { path = "../libcairo" }
corepack = { git = "https://github.com/jrasky/corepack.git", branch = "jrasky/serde-0.9-upgrade", default-features = false }
serde = { version = "1.0", default-features = false, features = ["collections"]}
serde_derive = "1.0"
syscall = { path = "../libsyscall" }
