[package]
name = "graphics"
version = "0.0.0"
authors = ["Tim Robinson <tim.g.robinson@gmail.com>"]

[lib]
path = "lib.rs"
test = false

[dependencies]
cairo = { path = "../libcairo" }
corepack = { version = ">= 0.2.1", default-features = false, features = ["collections"] }
os = { path = "../libos" }
serde = { version = "1.0", default-features = false, features = ["collections"] }
serde_derive = "1.0"
syscall = { path = "../libsyscall" }
