[package]
authors = ["Tim Robinson <tim.g.robinson@gmail.com>"]
name = "syscall"
version = "0.0.0"
edition = "2018"

[lib]
path = "lib.rs"
test = false

[dependencies]
libc = { path = "../liblibc" }

[features]
kernel = []
