(function() {var implementors = {};
implementors['std'] = ["impl&lt;'a, T&gt; <a class='trait' href='std/prelude/v1/trait.AsRef.html' title='std::prelude::v1::AsRef'>AsRef</a>&lt;T&gt; for <a class='enum' href='https://doc.rust-lang.org/nightly/core_collections/borrow/enum.Cow.html' title='core_collections::borrow::Cow'>Cow</a>&lt;'a, T&gt; <span class='where'>where T: <a class='trait' href='https://doc.rust-lang.org/nightly/core_collections/borrow/trait.ToOwned.html' title='core_collections::borrow::ToOwned'>ToOwned</a> + ?<a class='trait' href='std/prelude/v1/trait.Sized.html' title='std::prelude::v1::Sized'>Sized</a></span>","impl <a class='trait' href='std/prelude/v1/trait.AsRef.html' title='std::prelude::v1::AsRef'>AsRef</a>&lt;str&gt; for <a class='struct' href='std/prelude/v1/struct.String.html' title='std::prelude::v1::String'>String</a>","impl <a class='trait' href='std/prelude/v1/trait.AsRef.html' title='std::prelude::v1::AsRef'>AsRef</a>&lt;[u8]&gt; for <a class='struct' href='std/prelude/v1/struct.String.html' title='std::prelude::v1::String'>String</a>","impl&lt;T&gt; <a class='trait' href='std/prelude/v1/trait.AsRef.html' title='std::prelude::v1::AsRef'>AsRef</a>&lt;<a class='struct' href='std/prelude/v1/struct.Vec.html' title='std::prelude::v1::Vec'>Vec</a>&lt;T&gt;&gt; for <a class='struct' href='std/prelude/v1/struct.Vec.html' title='std::prelude::v1::Vec'>Vec</a>&lt;T&gt;","impl&lt;T&gt; <a class='trait' href='std/prelude/v1/trait.AsRef.html' title='std::prelude::v1::AsRef'>AsRef</a>&lt;[T]&gt; for <a class='struct' href='std/prelude/v1/struct.Vec.html' title='std::prelude::v1::Vec'>Vec</a>&lt;T&gt;","impl&lt;T&gt; <a class='trait' href='std/prelude/v1/trait.AsRef.html' title='std::prelude::v1::AsRef'>AsRef</a>&lt;T&gt; for <a class='struct' href='std/prelude/v1/struct.Box.html' title='std::prelude::v1::Box'>Box</a>&lt;T&gt; <span class='where'>where T: ?<a class='trait' href='std/prelude/v1/trait.Sized.html' title='std::prelude::v1::Sized'>Sized</a></span>","impl&lt;T&gt; <a class='trait' href='std/prelude/v1/trait.AsRef.html' title='std::prelude::v1::AsRef'>AsRef</a>&lt;T&gt; for <a class='struct' href='std/sync/struct.Arc.html' title='std::sync::Arc'>Arc</a>&lt;T&gt; <span class='where'>where T: ?<a class='trait' href='std/prelude/v1/trait.Sized.html' title='std::prelude::v1::Sized'>Sized</a></span>","impl&lt;T&gt; <a class='trait' href='std/prelude/v1/trait.AsRef.html' title='std::prelude::v1::AsRef'>AsRef</a>&lt;T&gt; for <a class='struct' href='https://doc.rust-lang.org/nightly/alloc/rc/struct.Rc.html' title='alloc::rc::Rc'>Rc</a>&lt;T&gt; <span class='where'>where T: ?<a class='trait' href='std/prelude/v1/trait.Sized.html' title='std::prelude::v1::Sized'>Sized</a></span>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
