language: rust

rust:
    - stable
    - nightly

sudo: false

notifications:
    email:
        on_success: never
        on_failure: always

script:
    - '[ "$TRAVIS_RUST_VERSION" != "nightly" ] || cargo build --features no_std'
    - '[ "$TRAVIS_RUST_VERSION" != "nightly" ] || cargo test --features no_std'
    - cargo build
    - cargo test
    - cargo doc --no-deps
    - rustdoc --test README.md -L target/debug
