[package]
authors = ["Tim Robinson <tim.g.robinson@gmail.com>"]
name = "hello"
version = "0.0.0"
edition = "2018"

[dependencies]
alloc_system = { path = "../../liballoc_system" }
rt = { path = "../../librt" }
std = { path = "../../libstd" }
