[package]
authors = ["Tim Robinson <tim.g.robinson@gmail.com>"]
name = "graphics_client"
version = "0.0.0"

[[bin]]
name = "graphics_client"
path = "main.rs"
test = false

[dependencies]
alloc_system = { path = "../../liballoc_system" }
cairo = { path = "../../libcairo" }
graphics = { path = "../../libgraphics" }
os = { path = "../../libos" }
syscall = { path = "../../libsyscall" }
