[package]
name = "libc"
version = "0.0.0"
authors = ["Tim Robinson <tim.g.robinson@gmail.com>"]

[lib]
name = "libc"
path = "lib.rs"
test = false

[dependencies]
core = { path = "../../rust/src/libcore" }
