[package]
authors = ["Tim Robinson <tim.g.robinson@gmail.com>"]
name = "hello"
version = "0.0.0"
edition = "2018"

[dependencies]
alloc_system = { path = "../alloc_system" }
rt = { path = "../rt" }
std = { path = "../std" }
