[package]
authors = ["Tim Robinson <tim.g.robinson@gmail.com>"]
name = "std"
version = "0.0.0"
edition = "2018"

[lib]
path = "lib.rs"
test = false

[dependencies]
libc = { path = "../libc" }
os = { path = "../os" }
syscall = { path = "../syscall" }
